title: Jekyll Showcase
remote_theme: pages-themes/cayman@v0.2.0

repository: RichDom2185/jekyll-showcase
markdown: kramdown

description: A showcase of my GitHub Pages-compatible Jekyll "plugins".

plugins:
  - jemoji
  - jekyll-remote-theme
